name: 'AWS Ansible'

on:
  workflow_run:
    workflows:
      - aws
    types:
      - completed
    branches:
      - main

jobs:
  node:
    name: 'AWS Ansible'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: aws.yml
          workflow_conclusion: success
          name: terraform

      - id: host
        env:
          SSH: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
            host=$(grep "ansible_ip_addr" terraform.output | awk -F  ":" '{print $1}' )
            host=${host//'ansible_ip_addr = "'}
            host=${host//'"'}
            echo $host >> ansible/hosts
            echo "$SSH" > ansible/key.pem
            chmod 400 ansible/key.pem

      - name: Ansible
        uses: saubermacherag/ansible-playbook-docker-action@v1.3
        with:
          playbookName: 'ansible/deployment.yml'
          inventoryFile: 'ansible/hosts'
          keyFile: 'ansible/key.pem'

      - name: itea_exam_1
        uses: actions/checkout@v2
        docker_container:
          name: node-js
          image: crycrime/devops_adv
          pull: true
          state: started
          ports:
            - "80:8080"
